### ISSUE TITLE
?expand behaviour for /items/{itemId}

### ISSUE THREAD

**Issue by DaveBudenberg** [MITLibraries/backrest#45]
Behaviour of expand parameter for /items/{_itemId_} differs from DSpace 5.4:
1. name element is only populated if expand=metadata is used (DSpace 5.4 populates always)
2. ?expand=all fails
3. ?expand=parentCommunityList fails

**Comment by richardrodgers** [comment]
Note to HB: I think it is possible that #3 above is caused by issue #49 - I will have a PR shortly
