### ISSUE TITLE
/bitstreams/{bitstreamId}/policy response is inconsistent

### ISSUE THREAD

**Issue by DaveBudenberg** [MITLibraries/backrest#47]
The response for this call looks inconsistent with DSpace 5.4 REST API (see 
[Bitstreams policy sample.txt](https://github.com/MITLibraries/backrest/files/427047/Bitstreams.policy.sample.txt)
):
1. schema looks different to DSpace 5.4 data (rpName, rpDescription?)
2. unclear about values for epersonId, groupId
3. capitalisation for action, rpType values?

**Comment by richardrodgers** [comment]
Thanks. Reactions:
Re 1: rpName & rpDescription were added to the DSpace data model around version 3, which was why we included them. But as the 5.4 REST API does not expose them, we will just remove them from backrest entirely.
Re 2: Will investigate - but these are database values which might not match across systems.
Re 3: will change capitalization to match 5.4 REST API
