### ISSUE TITLE
Capitalisation issue with resourcePolicy/resourcepolicy

### ISSUE THREAD

**Issue by DaveBudenberg** [MITLibraries/backrest#62]
When obtaining bitstream policy data using XML format, DSpace 5.4 REST API uses an element 'resourcePolicies'. Backrest returns a 'resourcepolicy' element, which doesn't match the same xpath... 
(This looks like an inconsistency in the DSpace API, given that it returns 'resourcepolicy' elements with 'resourcePolicies', but Backrest must reflect the same behaviour as the 'official' api.)

**Comment by richardrodgers** [comment]
Just to make sure we are covering the right cases here, there are 2 'container' labels for policies in API results (I think): first is the response to URLs like:

http://repo-dev-1.mit.edu/bitstreams/230253/policy

Backrest currently return results like:

```
<resourcepolicies>
<resourcepolicy>
<id>1824826</id>
 ...
</resourcepolicy>
</resourcepolicies>
```

Note that the container element is 'resourcepolicies' (no capital 'P') - this I believe is discrepancy with the official REST API you are reporting.

The second context is URLs like:

http://repo-dev-1.mit.edu/bitstreams/230253?expand=policies

where backrest returns a container element with the name 'policies' (matching the query parameter name). I want to confirm that that context is _not_ the concern here.

Thanks

**Comment by DaveBudenberg** [comment]
Apologies - I see my wording was not clear. Yes, I can confirm that I am referring to case 1 above.

**Comment by richardrodgers** [comment]
No problem - just wanted to make sure we were fixing where it was broken. Redeploy with the fix shortly.

**Comment by DaveBudenberg** [comment]
Many thanks!
